# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2

# Mod Properties
mod_version=1.0.0
maven_group=com.github.TheRedBrain
archives_base_name=rpg-class-selection

# Dependencies
fabric_api_version=0.116.2+1.21.1
tiny_config_version=3.1.0-fabric
cloth_config_version=15.0.140
player_animator_version=2.0.0-alpha1+1.21
spell_power_version=1.4.6+1.21.1-fabric
spell_engine_version=1.9.0+1.21.1-fabric
fzzy_config_version=0.7.3+1.21
slot_customization_api_version=2.2.0
rpg_inventory_version=2.10.0
